# Imagem base
FROM node:20 AS development

# Diretório de trabalho
WORKDIR /app

# Copiando apenas arquivos de dependências
COPY package*.json ./

# Instalando dependências globais e locais
RUN npm install -g @angular/cli@17.2.0 && npm install

# Copiando o restante do código
COPY . .

# Expondo a porta para o Angular
EXPOSE 4200

# Inicialização do servidor Angular
CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "8200", "--disable-host-check", "--poll", "2000"]
