version: "3.8"

services:
  estate-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: estate-dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8200:8200"
    environment:
      - NODE_ENV=development
